<?php get_header(); $assets=get_template_directory_uri().'/images/abayas/'; ?>
<main>
<section class="hero fashion-hero"><div class="hero-copy"><span class="eyebrow">HAYA2 · THE SILHOUETTE EDIT</span><h1>Presence,<br><em>in every fold.</em></h1><p>Beautifully flowing silhouettes.<br>Thoughtful details. Abayas that feel like you.</p><a class="button" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">Discover the collection &nbsp; ↗</a><span class="hero-note">01 / THE FLOWING SILHOUETTE</span></div><div class="hero-image"><img fetchpriority="high" src="<?php echo esc_url($assets.'abaya-6.jpg'); ?>" alt="Flowing black abaya against a burgundy backdrop"><span class="hero-caption">The flowing abaya · AED 275</span></div></section>
<div class="benefits"><span>✧ Abayas, thoughtfully selected</span><span>UAE delivery · AED pricing</span><span>Free delivery from AED 300</span><span>S · M · L · XL</span></div>
<section class="section"><div class="section-heading"><div><span class="eyebrow">Find your silhouette</span><h2>For every version of you.</h2></div><a href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">All abayas ↗</a></div><div class="category-grid fashion-collections">
<?php foreach ([['Everyday','everyday',5,'Effortless, from day to day'],['Occasion','occasion',2,'A little more extraordinary'],['Signature','signature',3,'Details that make it yours'],['Light tones','light-tones',7,'A softer point of view']] as [$label,$slug,$image,$line]) { ?><a class="category" href="<?php echo esc_url(home_url('/?product_cat='.$slug)); ?>"><img loading="lazy" src="<?php echo esc_url($assets.'abaya-'.$image.'.jpg'); ?>" alt="<?php echo esc_attr($label.' abaya collection'); ?>"><h3><?php echo esc_html($label); ?> ↗</h3><small><?php echo esc_html($line); ?></small></a><?php } ?></div></section>
<section class="fashion-edit"><div class="fashion-edit-image"><img loading="lazy" src="<?php echo esc_url($assets.'abaya-2.jpg'); ?>" alt="Burgundy-backed occasion abaya with a flowing silhouette"></div><div class="fashion-edit-copy"><span class="eyebrow">02 / THE OCCASION EDIT</span><h2>A moment.<br>A silhouette.<br><em>Entirely yours.</em></h2><p>Explore the occasion collection: expressive details, a graceful line, and room to move.</p><a class="button" href="<?php echo esc_url(home_url('/?product_cat=occasion')); ?>">Discover occasion pieces ↗</a></div></section><section class="section collection-edit"><div class="section-heading"><div><span class="eyebrow">The collection</span><h2>Your next favourite abaya.</h2></div><a href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">Shop the edit ↗</a></div><?php echo do_shortcode('[products limit="8" columns="4" category="abayas" orderby="menu_order" order="ASC"]'); ?></section>
<section class="story" id="our-story"><img loading="lazy" src="<?php echo esc_url($assets.'abaya-8.jpg'); ?>" alt="Light lilac patterned abaya in a softly lit setting"><div class="story-copy"><span class="eyebrow">The Haya2 point of view</span><h2>Grace in<br>every detail.</h2><p>From the ease of an everyday black abaya to the quiet beauty of an occasion piece, Haya2 celebrates flowing shapes and individual expression.</p><p>A wardrobe built around one beautiful essential.</p><a href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">Find your silhouette ↗</a></div></section>
</main><?php get_footer(); ?>
